### ISSUE TITLE
Change Default Locations

### ISSUE THREAD

**Issue by GeekMasher** [advanced-security/gh-codeql-scan#4]
We might want `codeql-databases` and `codeql-results` to be changed to other default locations such as `/tmp/codeql-scan/{name}/`.

- https://github.com/advanced-security/gh-codeql-scan/blob/main/gh-codeql-scan#L8
- https://github.com/advanced-security/gh-codeql-scan/blob/main/gh-codeql-scan#L11

**Comment by aegilops** [comment]
Yep, looks like a good proposal.

I think you could just look to see if that env is already set and use it as-is, or provide the default.

Alternatively you can accept an argument.

**Comment by GeekMasher** [comment]
Complete in v0.2
